embeddings:
  path: sentence-transformers/nli-mpnet-base-v2

nop:

weaviate_txtai.client.Weaviate:
  url: http://weaviate:8080

workflow:
  index:
    batch: 2500
    tasks:
    - action: [nop, transform]
      unpack: False
    - action: weaviate_txtai.client.Weaviate
      unpack: False
  search:
    tasks:
    - action: transform
    - action: weaviate_txtai.client.Weaviate
      args: [search]
 