version: '3.4'
services:
  txtai-api:
    build:
      context: .
      dockerfile: txtai-api.Dockerfile
    ports:
    - 8000:8000
    volumes:
      - ./app.yml:/app/app.yaml
      - ./client.py:/app/client.py
      - ./.cache:/models
    environment:
      - CONFIG=/app/app.yaml
      - TRANSFORMERS_CACHE=/models
    depends_on:
      - weaviate

  weaviate:
    image: semitechnologies/weaviate:1.16.6
    ports:
    - 8080:8080
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
